/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./App.tsx",
    "./main.tsx",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
    "./constants.tsx"
  ],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      spacing: {
        'sidebar-width': '18rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
      },
      fontFamily: {
        head: ['Sora', 'Trebuchet MS', 'sans-serif'],
        body: ['"Source Sans 3"', 'Segoe UI', 'Arial', 'sans-serif'],
        sans: ['"Source Sans 3"', 'Segoe UI', 'Arial', 'sans-serif'],
        serif: ['Sora', 'Trebuchet MS', 'sans-serif'],
        mono: ['"DM Mono"', '"JetBrains Mono"', 'monospace'],
        'display-lg': ['Sora', 'sans-serif'],
        'display-md': ['Sora', 'sans-serif'],
        'display-sm': ['Sora', 'sans-serif'],
        'headline-md': ['Sora', 'sans-serif'],
        'headline-sm': ['Sora', 'sans-serif'],
        'body-lg': ['"Source Sans 3"', 'sans-serif'],
        'body-md': ['"Source Sans 3"', 'sans-serif'],
        'body-sm': ['"Source Sans 3"', 'sans-serif'],
        'label-caps': ['"Source Sans 3"', 'sans-serif'],
        'label-mono': ['"DM Mono"', 'monospace'],
        'data-metric-lg': ['Sora', 'monospace'],
        'data-metric-md': ['Sora', 'monospace'],
        'data-metric-sm': ['Sora', 'monospace'],
      },
      colors: {
        // Kazira Official Design Tokens
        bg: 'var(--bg)',
        surface: 'var(--surface)',
        ink: 'var(--ink)',
        ink2: 'var(--ink2)',
        line: 'var(--line)',
        'btn-bg': 'var(--btn-bg)',
        'btn-fg': 'var(--btn-fg)',
        recover: 'var(--recover)',
        leak: 'var(--leak)',
        'leak-bg': 'var(--leak-bg)',
        ok: 'var(--ok)',
        'ok-bg': 'var(--ok-bg)',
        focus: 'var(--focus)',

        // Semantic bindings with Forest Green & Warm Gold
        'primary': '#005235',
        'primary-container': '#1d6b4a',
        'on-primary': '#FFFFFF',
        'secondary': 'var(--leak)',
        'secondary-container': 'var(--leak-bg)',
        'accent': '#005235',
        'accent2': '#1d6b4a',
        'gold': '#c58c2b',
        'on-surface': 'var(--ink)',
        'on-surface-variant': 'var(--ink2)',
        'outline': 'var(--ink2)',
        'outline-variant': 'var(--line)',
        'surface-container-lowest': 'var(--surface-container-lowest, #FFFFFF)',
        'surface-container-low': 'var(--surface-container-low, #FAFAFA)',
        'surface-container': 'var(--surface-container, #F8F9FA)',
        'surface-container-high': 'var(--surface-container-high, #F3F4F6)',
        'surface-container-highest': 'var(--surface-container-high, #E5E7EB)',
      }
    },
  },
  plugins: [],
}
