/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./App.tsx",
    "./main.tsx",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./utils/**/*.{js,ts,jsx,tsx}",
    "./services/**/*.{js,ts,jsx,tsx}",
    "./constants.tsx"
  ],
  theme: {
    extend: {
      spacing: {
        'sidebar-width': '18rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
        'space-2xs': '0.125rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '0.75rem',
        'space-base': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
      },
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        serif: ['"DM Serif Display"', 'Newsreader', 'serif'],
        mono: ['"DM Mono"', '"JetBrains Mono"', 'monospace'],
        'display-lg': ['Newsreader', '"DM Serif Display"', 'serif'],
        'display-md': ['Newsreader', '"DM Serif Display"', 'serif'],
        'display-sm': ['Newsreader', '"DM Serif Display"', 'serif'],
        'headline-md': ['Newsreader', '"DM Serif Display"', 'serif'],
        'body-lg': ['Outfit', 'sans-serif'],
        'body-md': ['Outfit', 'sans-serif'],
        'body-sm': ['Outfit', 'sans-serif'],
        'label-caps': ['Outfit', 'sans-serif'],
        'label-mono': ['"JetBrains Mono"', '"DM Mono"', 'monospace'],
        'data-metric-lg': ['"JetBrains Mono"', '"DM Mono"', 'monospace'],
        'data-metric-md': ['"JetBrains Mono"', '"DM Mono"', 'monospace'],
        'data-metric-sm': ['"JetBrains Mono"', '"DM Mono"', 'monospace'],
      },
      colors: {
        // Warm, grounded institutional palette - eliminating harsh pure white
        ink: '#111110',
        ink2: '#3d3d38',
        ink3: '#6b6b65',
        surface: '#f7f4ef',
        surface2: '#eeeae4',
        surface3: '#e4dfd8',
        accent: '#005235',
        accent2: '#1d6b4a',
        'accent-light': '#e8f2ec',
        'accent-pale': '#f0faf5',
        warn: '#9a4600',
        'warn-light': '#ffdbc9',
        gold: '#5a4300',
        'gold-light': '#ffdf99',
        border: '#bfc9c0',
        border2: '#d8d3cc',

        // New Design System Semantic Colors
        'primary': '#005235',
        'primary-container': '#1d6b4a',
        'on-primary': '#fcfbfa',
        'on-primary-container': '#9de9bf',
        'primary-fixed': '#a7f3c9',
        'primary-fixed-dim': '#8bd6ae',
        'on-primary-fixed': '#002113',

        'secondary': '#9a4600',
        'secondary-container': '#d96414',
        'secondary-fixed': '#ffdbc9',
        'secondary-fixed-dim': '#ffb68c',
        'on-secondary': '#fcfbfa',
        'on-secondary-container': '#6d3000',
        'on-secondary-fixed': '#321200',

        'tertiary': '#5a4300',
        'tertiary-container': '#775a00',
        'tertiary-fixed': '#ffdf99',
        'tertiary-fixed-dim': '#eec04e',
        'on-tertiary': '#fcfbfa',
        'on-tertiary-container': '#ffd36a',

        'surface-dim': '#ded9d2',
        'surface-bright': '#faf7f2',
        'surface-variant': '#e4dfd8',
        'surface-container-lowest': '#fbf9f6',
        'surface-container-low': '#f5f1eb',
        'surface-container': '#eeeae4',
        'surface-container-high': '#e7e2db',
        'surface-container-highest': '#e0dad2',

        'on-surface': '#1c1c1a',
        'on-surface-variant': '#3f4943',
        'outline': '#6f7a72',
        'outline-variant': '#c5cec7',
        'inverse-surface': '#31302f',
        'inverse-on-surface': '#f3f0ee',
      }
    },
  },
  plugins: [],
}
