import React from 'react';

const Documentation: React.FC = () => {
  return (
    <div className="prose prose-sm max-w-none text-ink3">
      <h3 className="text-lg font-bold text-ink mb-4 font-serif">Help Center & Documentation</h3>
      
      <h4 className="font-bold text-ink mt-6 mb-2">Getting Started</h4>
      <p className="mb-4">Welcome to Kazira Clinical Intelligence. To get started, simply paste your clinic's raw data (CSV, Markdown, or plain text) into the input area on the main dashboard.</p>

      <h4 className="font-bold text-ink mt-6 mb-2">Supported Data Formats</h4>
      <ul className="list-disc pl-5 mb-4 space-y-1">
        <li><strong>CSV:</strong> Export directly from your Practice Management System (PMS). Ensure it includes columns for Date, Procedure, Practitioner, and Amount.</li>
        <li><strong>Text/Markdown:</strong> You can paste raw notes or structured text. Our AI will automatically extract the relevant metrics.</li>
      </ul>

      <h4 className="font-bold text-ink mt-6 mb-2">Understanding the Report</h4>
      <p className="mb-4">Once generated, the report provides:</p>
      <ul className="list-disc pl-5 mb-4 space-y-1">
        <li><strong>Executive Summary:</strong> A high-level overview of the week's performance.</li>
        <li><strong>Revenue Leakage:</strong> Identification of unbilled procedures or missed follow-ups.</li>
        <li><strong>Practitioner Performance:</strong> Breakdown of revenue generated by each clinician.</li>
      </ul>

      <h4 className="font-bold text-ink mt-6 mb-2">Need Help?</h4>
      <p className="mb-4">If you encounter any issues or need assistance formatting your data, please contact our support team at <a href="mailto:support@kazira.io" className="text-accent hover:underline">support@kazira.io</a>.</p>
    </div>
  );
};

export default Documentation;
